net: implement ResolveIPAddr with a stub for lookupProtocol
tinygo-org/net pull request #24
Opened 2024-04-08 21:22 UTC by paralin

2024-04-08 21:39 UTC, paralin commented
Okay, after a couple fixes, got it right now 👍🏽

2024-04-09 01:37 UTC, scottfeldman requested changes
Thank you for the PR.  Some inline comments...

2024-04-09 01:37 UTC, scottfeldman commented on tcpsock.go
> +	if network == "" { // a hint wildcard for Go 1.0 undocumented behavior
We can probably skip everything here except returning the "not implemented" error.

2024-04-09 01:37 UTC, scottfeldman commented on tcpsock.go
> +	return nil, errors.New("tcpsock:ResolveIPAddr not implemented")
s/tcpsock/ipsock

2024-04-09 01:37 UTC, scottfeldman commented on tcpsock.go
> +func ResolveIPAddr(network, address string) (*IPAddr, error) {
Move this func to iprawsock.go please.  I'm trying to keep things aligned with where things are in the upstream src/net repo, for comparison sake.

2025-01-05 00:25 UTC, scottfeldman commented
Hi @paralin, added PR#36 to resolve this PR.  PR#36 has the review changes.  Mostly just moved changes into proper files to keep synced with Go upstream.

2025-01-05 07:18 UTC, closed without merging

2025-01-05 07:18 UTC, paralin commented
Ok see #36 then 👍🏽